modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/XiaoXianHW/EasyLAN/issues"

[[mods]]
modId="easylan"
version="1.5"
displayName="EasyLAN"
displayURL="https://github.com/XiaoXianHW/EasyLAN"
authors="XiaoXian"
description='''A Custom LAN Server Mod!:DDD'''
